### ISSUE TITLE
Creating a Labeller account with kbsky

### ISSUE THREAD

**Issue by CrystalSpore** [uakihir0/kbsky#101]
I see several reference to Labels, but as far as I can tell from reading through the reference notes in the classes, I believe this is just for getting labels & not for applying labels. Would my assessment be correct?

(Reference to ATProto docs for label distribution: https://atproto.com/specs/label#label-distribution-endpoints )

**Comment by uakihir0** [comment]
There are currently no plans to support the creation of Labeler accounts.
We have completed support for accept labeler.
