### ISSUE TITLE
Unable to import 'core' into java/maven project

### ISSUE THREAD

**Issue by MarcFletcher** [uakihir0/kbsky#109]
Many thanks for your library.

When adding this library as a maven dependency to an existing Java (17) project:

```
<dependency>
  <groupId>work.socialhub.kbsky</groupId>
  <artifactId>core</artifactId>
  <version>0.2.0</version>
</dependency>
```

And building, at just this step it compiles successfully. The dependency is resolved and added into the .m2 local cache, as you would expect.

When trying to use the dependency however, in Intellij, it fails to resolve any of the expected library packages.

For example writing:

`import work.socialhub.kbsky.*;`

Results in the following errors:

`package work.socialhub.kbsky does not exist`

I'm not overly familiar with using a Kotlin library in a Java project but my expectation is that it works just the same as others.

Following various debugging guides I have tried also including the following dependency, but it didn't change the error being shown:

```
<dependency>
  <groupId>org.jetbrains.kotlin</groupId>
  <artifactId>kotlin-stdlib</artifactId>
  <version>2.0.21</version>
</dependency>
```

Can i please ask if you have any advice? Many thanks.

**Comment by MarcFletcher** [comment]
Some additional information if it's helpful. I have tested my approach to including a kotlin dependency using https://github.com/jsoizo/kotlin-csv:

```
        <dependency>
            <groupId>com.jsoizo</groupId>
            <artifactId>kotlin-csv-jvm</artifactId>
            <version>1.10.0</version>
        </dependency>
```

This works successfully and I can use the library from Java. 

When I inspect the project libraries in Intellij I can see the following for the internal structure of the `kotlin-csv-jvm` library:

![expected_kotlin_structure_in_project_structure](https://github.com/user-attachments/assets/7795648a-6114-4e48-84aa-c179cc98c5be)

This shows the expected classes.

When I look at the same structure for this library, kbsky, I see a large number of `*.knm` files that I'm unfamiliar with:

![unexpected_kotlin_structure_in_project_structure](https://github.com/user-attachments/assets/55fe7e9d-9774-464a-8385-a035504011a5)

Does this help at all?

**Comment by MarcFletcher** [comment]
This appears to be a similar problem but there are no answers yet - https://stackoverflow.com/questions/79152920/maven-cannot-resolve-a-kotlin-library-of-knm-files

**Comment by uakihir0** [comment]
Hi.
Could you try `core-jvm`?
https://mvnrepository.com/artifact/work.socialhub.kbsky/core-jvm/0.2.0

**Comment by MarcFletcher** [comment]
Many thanks for the quick reply. Apologies for not spotting the alternative dependency. A quick initial test appears to work. If I have any other issues I'll get back to you.
