### ISSUE TITLE
Will this library work in a plain old Java server application?

### ISSUE THREAD

**Issue by preslavrachev** [uakihir0/kbsky#111]
In the lack of suitable BlueSky SDKs, I ended up checking yours out. I added it as a Maven dependency to Quarkus app I am working on, but it looks like I am not able to use it, even though Maven would fetch it without any issues.

**Comment by uakihir0** [comment]
@preslavrachev 
Probably the same problem as https://github.com/uakihir0/kbsky/issues/109 . Try using `core-jvm` `stream-jvm`.

**Comment by preslavrachev** [comment]
Looks like this worked, thanks!

Just a heads up: I added a PR with a few small additions to the documentation: https://github.com/uakihir0/kbsky/pull/112
