### ISSUE TITLE
No "aspectRatio" in EmbedImagesImage.kt

### ISSUE THREAD

**Issue by xiujunma** [uakihir0/kbsky#116]
There are big paddings around the image that I uploaded through this library, and the images uploaded through web look fine.
<img width="573" alt="Screenshot 2024-12-07 at 6 37 44 PM" src="https://github.com/user-attachments/assets/1a1b38cc-ed7a-40f8-8a2c-46210cff22da">

It seems there should be an aspectRatio property for EmbedImagesImage
https://docs.bsky.app/docs/tutorials/creating-a-post#images-embeds
```ts
const image = 'data:image/png;base64,...'
const { data } = await agent.uploadBlob(convertDataURIToUint8Array(image), {
  encoding,
})
await agent.post({
  text: 'I love my cat',
  embed: {
    $type: 'app.bsky.embed.images',
    images: [
      // can be an array up to 4 values
      {
        alt: 'My cat mittens', // the alt text
        image: data.blob,
        aspectRatio: {
          // a hint to clients
          width: 1000,
          height: 500
        }
    }],
  },
  createdAt: new Date().toISOString()
})
```

**Comment by xiujunma** [comment]
```kt
package work.socialhub.kbsky.model.app.bsky.embed

import kotlinx.serialization.Serializable
import work.socialhub.kbsky.model.share.Blob

@Serializable
class EmbedImagesImage {
    var image: Blob? = null
    var alt: String? = null
    var aspectRatio: EmbedDefsAspectRatio? = null
}
```

Will this be working without other changes? How can I test this code?

**Comment by xiujunma** [comment]
https://github.com/uakihir0/kbsky/pull/119
I have tested this, but I couldn't unit tests.

**Comment by uakihir0** [comment]
Thanks for the PR!

I checked https://github.com/uakihir0/kbsky/pull/119. I checked the operation and it was OK, so I merged it! Thank you very much.
